"""
profile_analyzer.py
====================
Adds LinkedIn / Portfolio analysis + Job Matching on top of Vision Careers AI.

This module is 100% additive — it does not import from or modify app.py,
roadmap.py, or train_model.py. It reuses the SAME trained model.pkl
(pipeline + career_metadata) that already powers the resume analyzer, so
"job match %" is generated by the existing ML model, not a new stub.

Public functions used by app.py:
    - extract_text_from_url(url)          -> str
    - fetch_linkedin_public_snapshot(url)  -> dict
    - score_profile(text)                 -> dict
    - match_jobs(text, pipeline, metadata) -> pandas.DataFrame
"""

import re
import requests
from html import unescape

try:
    from bs4 import BeautifulSoup
    _HAS_BS4 = True
except ImportError:
    _HAS_BS4 = False

import pandas as pd


# ============================================================
# GENERIC WEB TEXT EXTRACTION  (for portfolio sites)
# ============================================================

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    )
}


def _strip_tags_fallback(html: str) -> str:
    """Very small HTML->text fallback if bs4 isn't installed."""
    html = re.sub(r"(?is)<(script|style).*?>.*?(</\1>)", " ", html)
    text = re.sub(r"(?s)<[^>]+>", " ", html)
    return unescape(re.sub(r"\s+", " ", text)).strip()


def extract_text_from_url(url: str, timeout: int = 10) -> str:
    """
    Fetch a public web page (portfolio site, GitHub profile, personal
    site, etc.) and return its visible text. Returns "" on any failure
    so the caller can degrade gracefully instead of crashing the app.
    """
    if not url:
        return ""

    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    try:
        resp = requests.get(url, headers=HEADERS, timeout=timeout)
        resp.raise_for_status()
    except Exception:
        return ""

    if _HAS_BS4:
        soup = BeautifulSoup(resp.text, "html.parser")
        for tag in soup(["script", "style", "noscript"]):
            tag.decompose()
        text = soup.get_text(separator=" ")
        text = re.sub(r"\s+", " ", text).strip()
    else:
        text = _strip_tags_fallback(resp.text)

    return text


# ============================================================
# LINKEDIN HANDLING
# ============================================================
# LinkedIn blocks unauthenticated scraping of full profile data, so we
# can't pull someone's real experience/skills just from a URL. What we
# CAN reliably do without violating LinkedIn's access rules:
#   1) Read public Open Graph meta tags (title/description) as a light
#      signal when a URL is pasted.
#   2) Strongly recommend the user paste their profile text, or upload
#      the PDF LinkedIn itself generates via "Save to PDF" on any
#      profile (this reuses the app's EXISTING extract_text_from_pdf
#      function in app.py — untouched).

def fetch_linkedin_public_snapshot(url: str, timeout: int = 10) -> dict:
    """
    Best-effort, non-invasive fetch of public LinkedIn OG meta tags.
    Returns {"title": ..., "description": ..., "ok": bool}.
    This will legitimately return little/nothing for most profiles —
    that's expected LinkedIn behavior, not a bug.
    """
    result = {"title": "", "description": "", "ok": False}
    if not url:
        return result
    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    try:
        resp = requests.get(url, headers=HEADERS, timeout=timeout)
        if resp.status_code != 200 or not _HAS_BS4:
            return result
        soup = BeautifulSoup(resp.text, "html.parser")

        og_title = soup.find("meta", property="og:title")
        og_desc = soup.find("meta", property="og:description")

        if og_title and og_title.get("content"):
            result["title"] = og_title["content"].strip()
        if og_desc and og_desc.get("content"):
            result["description"] = og_desc["content"].strip()

        result["ok"] = bool(result["title"] or result["description"])
    except Exception:
        pass

    return result


# ============================================================
# PROFILE QUALITY SCORE  (LinkedIn text, portfolio text, or resume)
# ============================================================

_ACTION_VERBS = [
    "led", "built", "designed", "developed", "launched", "improved",
    "increased", "reduced", "optimized", "created", "managed", "shipped",
    "architected", "implemented", "automated", "scaled", "mentored",
    "delivered", "spearheaded", "drove", "owned", "migrated"
]

_SECTION_KEYWORDS = {
    "summary":     ["summary", "about", "objective", "profile"],
    "experience":  ["experience", "work history", "employment"],
    "education":   ["education", "degree", "university", "college", "b.tech", "bachelor", "master"],
    "skills":      ["skills", "technologies", "tools", "stack"],
    "projects":    ["project", "projects", "portfolio"],
    "certs":       ["certification", "certified", "certificate"],
}

_CONTACT_PATTERNS = {
    "email":    r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",
    "linkedin": r"linkedin\.com/in/[A-Za-z0-9\-_%]+",
    "github":   r"github\.com/[A-Za-z0-9\-_]+",
    "website":  r"https?://[^\s]+",
    "phone":    r"(\+?\d[\d\-\s()]{8,}\d)",
}


def _quantified_achievements(text: str) -> int:
    """Counts phrases suggesting measurable impact, e.g. '30%', '$2M', '10x'."""
    patterns = [r"\d+%", r"\$\d+[km]?", r"\d+x\b", r"\d+\+?\s?(users|customers|clients|engineers|projects)"]
    count = 0
    for p in patterns:
        count += len(re.findall(p, text, flags=re.IGNORECASE))
    return count


def score_profile(text: str) -> dict:
    """
    Heuristic profile-quality scorer (0-100), inspired by how ATS /
    recruiter-facing tools grade LinkedIn & resume completeness.
    Fully local — no external AI call, so it works offline and free.

    Returns a dict with an overall score, 4 sub-scores (0-25 each),
    and human-readable tips for improvement.
    """
    text = (text or "").strip()
    if len(text) < 15:
        return {
            "overall": 0,
            "sub_scores": {"Completeness": 0, "Impact": 0, "Keyword Depth": 0, "Structure": 0},
            "tips": ["Add more content — paste your LinkedIn About/Experience "
                     "section or upload a PDF export to get a real score."],
            "word_count": 0,
        }

    text_lower = text.lower()
    word_count = len(text.split())
    tips = []

    # ---- 1) Completeness (sections present) — out of 25 ----
    sections_found = 0
    for section, keywords in _SECTION_KEYWORDS.items():
        if any(kw in text_lower for kw in keywords):
            sections_found += 1
    completeness = round((sections_found / len(_SECTION_KEYWORDS)) * 25)
    if sections_found < 3:
        tips.append("Add clear sections like Summary, Experience, Education, and Skills.")

    # ---- 2) Impact / quantified achievements — out of 25 ----
    verb_hits = sum(1 for v in _ACTION_VERBS if re.search(r"\b" + v + r"\b", text_lower))
    quant_hits = _quantified_achievements(text)
    impact_raw = verb_hits * 1.5 + quant_hits * 3
    impact = min(25, round(impact_raw))
    if quant_hits == 0:
        tips.append("Add measurable results (e.g. 'reduced load time by 30%', 'led a team of 5').")
    if verb_hits < 3:
        tips.append("Use more strong action verbs (built, led, launched, optimized...).")

    # ---- 3) Keyword depth vs. length — out of 25 ----
    length_score = min(15, word_count / 12)          # rewards substantive writing
    contact_bonus = 0
    for label, pattern in _CONTACT_PATTERNS.items():
        if re.search(pattern, text, flags=re.IGNORECASE):
            contact_bonus += 2
    keyword_depth = min(25, round(length_score + contact_bonus))
    if word_count < 80:
        tips.append("Your profile text is quite short — aim for a fuller About/Experience section.")
    if contact_bonus == 0:
        tips.append("Include a way to be reached or a link (email, GitHub, portfolio, LinkedIn).")

    # ---- 4) Structure / readability — out of 25 ----
    sentence_count = max(1, len(re.findall(r"[.!?]", text)))
    avg_sentence_len = word_count / sentence_count
    if 8 <= avg_sentence_len <= 28:
        structure = 25
    elif avg_sentence_len < 8:
        structure = 15
        tips.append("Sentences look very short/fragmented — expand on your bullet points.")
    else:
        structure = 12
        tips.append("Some sentences are very long — break them into concise bullet points.")

    overall = int(completeness + impact + keyword_depth + structure)

    if not tips:
        tips.append("Strong profile! Consider tailoring keywords per job you apply to.")

    return {
        "overall": overall,
        "sub_scores": {
            "Completeness": completeness,
            "Impact": impact,
            "Keyword Depth": keyword_depth,
            "Structure": structure,
        },
        "tips": tips,
        "word_count": word_count,
    }


# ============================================================
# JOB MATCHING  (reuses the EXISTING trained pipeline + metadata)
# ============================================================

def match_jobs(text: str, pipeline, metadata: dict) -> pd.DataFrame:
    """
    Runs the SAME TF-IDF + LogisticRegression pipeline already trained
    in train_model.py against the given profile text (resume, LinkedIn
    text, or portfolio text) and returns a full ranked job-match table
    for every known role — not just the top 1.

    Columns: Career, Match %, Salary Range, Difficulty,
             Matched Core Skills, Missing Core Skills
    """
    if not text or len(text.strip()) < 15:
        return pd.DataFrame(columns=[
            "Career", "Match %", "Salary Range", "Difficulty",
            "Matched Core Skills", "Missing Core Skills"
        ])

    probs = pipeline.predict_proba([text])[0]
    classes = pipeline.classes_

    rows = []
    text_lower = text.lower().replace(".", "").replace("+", "")

    for career, prob in zip(classes, probs):
        info = metadata.get(career, {})
        core_skills = info.get("core_skills", [])

        matched, missing = [], []
        for skill in core_skills:
            skill_clean = skill.lower().replace(".", "").replace("+", "")
            pattern = r"\b" + re.escape(skill_clean) + r"\b"
            if re.search(pattern, text_lower):
                matched.append(skill)
            else:
                missing.append(skill)

        rows.append({
            "Career": career,
            "Match %": round(prob * 100, 1),
            "Salary Range": info.get("salary_range", "N/A"),
            "Difficulty": info.get("difficulty", "N/A"),
            "Matched Core Skills": matched,
            "Missing Core Skills": missing,
        })

    df = pd.DataFrame(rows).sort_values(by="Match %", ascending=False).reset_index(drop=True)
    return df
